/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package calculadora;

/**
 *
 * @author Cecilia Carrasco
 */

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
import javax.swing.border.EmptyBorder;

public class VentanaCalculadora extends javax.swing.JFrame {
    JTextField pantalla;
    double resultado;
    String operacion;
    JPanel panelNumeros, panelOperaciones;
    boolean nuevaOperacion = true;
    /** Creates new form VentanaCalculadora */
    public VentanaCalculadora() {
        super();
        setSize(250, 300);
	
	setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
	setResizable(false);
        
        JPanel panel = (JPanel) this.getContentPane();
	panel.setLayout(new BorderLayout());
        
        pantalla = new JTextField("0", 20);
	pantalla.setBorder(new EmptyBorder(4, 4, 4, 4));
	pantalla.setFont(new Font("Arial", Font.BOLD, 25));
	pantalla.setHorizontalAlignment(JTextField.RIGHT);
	pantalla.setEditable(false);
	pantalla.setBackground(Color.PINK);
	panel.add("North", pantalla);
        
        panelNumeros = new JPanel();
	panelNumeros.setLayout(new GridLayout(4, 3));
	panelNumeros.setBorder(new EmptyBorder(4, 4, 4, 4));
        
        for (int n = 9; n >= 0; n--) {
			BotonNumerico("" + n);
		}
        
        BotonNumerico(".");

	panel.add("Center", panelNumeros);

	panelOperaciones = new JPanel();
	panelOperaciones.setLayout(new GridLayout(6, 1));
	panelOperaciones.setBorder(new EmptyBorder(4, 4, 4, 4));

	BotonOperacion("+");
	BotonOperacion("-");
	BotonOperacion("*");
	BotonOperacion("/");
	BotonOperacion("=");
	BotonOperacion("CE");

	panel.add("East", panelOperaciones);

	validate();
    }
    private void BotonNumerico(String digito) {
		JButton btn = new JButton();
		btn.setText(digito);
		btn.addMouseListener(new MouseAdapter() {

			@Override
			public void mouseReleased(MouseEvent evt) {
				JButton btn = (JButton) evt.getSource();
				addnumero(btn.getText());
			}
		});

		panelNumeros.add(btn);
	}
    private void BotonOperacion(String operacion) {
		JButton btn = new JButton(operacion);
		btn.setForeground(Color.RED);

		btn.addMouseListener(new MouseAdapter() {

			@Override
			public void mouseReleased(MouseEvent evt) {
				JButton btn = (JButton) evt.getSource();
				operacion(btn.getText());
			}
		});

		panelOperaciones.add(btn);
	}
    private void addnumero(String digito) {
		if (pantalla.getText().equals("0") || nuevaOperacion) {
			pantalla.setText(digito);
		} else {
			pantalla.setText(pantalla.getText() + digito);
		}
		nuevaOperacion = false;
	}
    private void operacion(String tecla) {
		if (tecla.equals("=")) {
			calcularResultado();
		} else if (tecla.equals("CE")) {
			resultado = 0;
			pantalla.setText("");
			nuevaOperacion = true;
		} else {
			operacion = tecla;
			if ((resultado > 0) && !nuevaOperacion) {
				calcularResultado();
			} else {
				resultado = new Double(pantalla.getText());
			}
		}

		nuevaOperacion = true;
	}
    private void calcularResultado() {
		if (operacion.equals("+")) {
			resultado += new Double(pantalla.getText());
		} else if (operacion.equals("-")) {
			resultado -= new Double(pantalla.getText());
		} else if (operacion.equals("/")) {
			resultado /= new Double(pantalla.getText());
		} else if (operacion.equals("*")) {
			resultado *= new Double(pantalla.getText());
		}

		pantalla.setText("" + resultado);
		operacion = "";
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify                     
    // End of variables declaration                   
        public static void main (String[]args){
             VentanaCalculadora calculadora = new VentanaCalculadora();
             calculadora.setVisible(true);
        }
}
